config/routes.rb
Sakila::Application.routes.draw do

  root 'films#index'

  resources :actors
  resources :films
  resources :rentals do
    collection do
      get :returned
      get :unreturned
    end
  end
  resources :customers

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :films
    end
  end

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  include Filterable
  has_many :film_actors
  has_many :films, :through => :film_actors

  def full_name
    [first_name, last_name].join(" ").titleize
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :city
  belongs_to :country
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :film_categories
  has_many :films, :through => :film_categories
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  include Filterable
  has_many :rentals
  has_many :payments
  belongs_to :address

  def full_name
    [first_name, last_name].join(' ').titleize
  end
end

app/models/film.rb
class Film < ActiveRecord::Base
  include Filterable
  has_many :film_actors
  has_many :actors, :through => :film_actors
  has_one :inventory
  has_one :film_category
  has_one :category, :through => :film_category

  def to_s
    title.titleize
  end
end

app/models/film_actor.rb
class FilmActor < ActiveRecord::Base
  self.table_name = 'film_actor'
  before_save :set_last_updated_at
  belongs_to :actor
  belongs_to :film

  private

  def set_last_updated_at
    self.last_update = Time.now
  end
end

app/models/film_category.rb
class FilmCategory < ActiveRecord::Base
  self.table_name = "film_category"
  belongs_to :film
  belongs_to :category
end

app/models/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  included do
    scope :filter, ->(attribute, letter) { where("#{attribute} LIKE '#{letter}%'") if letter.present? }
  end
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :film
  belongs_to :store
  has_one :rental
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :customer
end

app/models/rental.rb
class Rental < ActiveRecord::Base
  belongs_to :customer
  delegate :full_name, :to => :customer, :prefix => true
  belongs_to :inventory
  has_one :film, :through => :inventory
  scope :unreturned, -> { where(:return_date => nil)}
  scope :returned, -> { where("return_date IS NOT NULL")}

  def due_date
    rental_date + duration.days
  end
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :inventories

  def films_in_inventory
    inventories.map(&:film)
  end

  def rentals
    inventories.map(&:rental)
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

  def index
    @actors = Actor.filter(:last_name, params[:letter]).page(params[:page])
  end

  def show
    @actor = Actor.find(params[:id])
  end
end

app/controllers/api/v1/films_controller.rb
class Api::V1::FilmsController < ApplicationController

  def index
    @films = Film.includes(:actors).page(params[:page])
  end

  def show
    @film = Film.includes(:actors).find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.filter(:last_name, params[:letter]).page(params[:page])
  end

  def show
    @customer = Customer.includes(:rentals => :film).find(params[:id])
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController

  def index
    term = params[:letter] || params[:term] # Filterable module uses different param than jQuery autocomplete on search box
    if params[:category_id]
      @category = Category.find(params[:category_id])
      films = @category.films
    else
      films = Film.all
    end
    @films = films.filter(:title, term).page(params[:page]).per(5)

    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    @film = Film.includes(:actors).find(params[:id])
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

  def returned
    @rentals = Rental.returned.includes([:customer, :film]).page(params[:page])
  end

  def unreturned
    @rentals = Rental.unreturned.includes([:customer, :film]).page(params[:page])
  end

  def show
    @rental = Rental.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/actors/index.html.erb
<h1>Actors</h1>

<%= render :partial => 'shared/last_name_filter', :locals => { :path => actors_path } %>

<% if @actors.any? %>

<table class="table table-condensed">
  <thead>
    <th>Id</th>
    <th>Name</th>
  </thead>
  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.id %></td>
        <td><%= link_to actor.full_name, actor_path(actor) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @actors, :params => { :letter => params[:letter] } %>

<% else %>

<p>No records found.</p>

<% end %>

app/views/actors/show.html.erb
<h1><%= @actor.full_name %></h1>

<% @actor.films.each do |film| %>
  <p><%= link_to film.to_s, film_path(film) %></p>
<% end %>

<%= link_to 'Back to actors', actors_path %>

app/views/customers/index.html.erb
<h1>Customers</h1>

<%= render :partial => 'shared/last_name_filter', :locals => { :path => customers_path } %>

<% if @customers.any? %>

<table class="table table-condensed">
  <thead>
    <th>Id</th>
    <th>Name</th>
    <th>Email</th>
    <th>Address</th>
    <th>Store</th>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= link_to customer.full_name, customer_path(customer) %></td>
        <td><%= customer.email.downcase %></td>
        <td><%= customer.address_id %></td>
        <td><%= customer.store_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @customers, :params => { :letter => params[:letter] } %>

<% else %>

<p>No records found.</p>

<% end %>

app/views/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="span9">
      <h1><%= @customer.full_name %></h1>
      <h3>Rental history</h3>
    </div>
    <div class="span3">
      <address>
        <%= @customer.address.address %><br>
        <%= "#{@customer.address.city.city}, #{@customer.address.district}" %><br>
        <%= @customer.address.country.country %><br>
        <abbr title="Phone">P:</abbr> <%= @customer.address.phone %><br>
        <%= mail_to @customer.email.downcase %>
      </address>
    </div>
  </div>
</div>

<% if @customer.rentals.unreturned.any? %>

<h3>Unreturned rentals</h3>

<table class="table table-condensed">
  <thead>
    <th>Rental ID</th>
    <th>Title</th>
    <th>Rental date</th>
  </thead>
  <tbody>
    <% @customer.rentals.unreturned.each do |rental| %>
      <tr>
        <td><%= link_to rental.to_param, rental_path(rental) %></td>
        <td><%= link_to rental.film, film_path(rental.film) %></td>
        <td><%= rental.rental_date.to_formatted_s(:db) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Returned rentals</h3>

<% end %>

<% if @customer.rentals.returned.any? %>

<table class="table table-condensed">
  <thead>
    <th>Rental ID</th>
    <th>Title</th>
    <th>Rental date</th>
    <th>Return date</th>
  </thead>
  <tbody>
    <% @customer.rentals.returned.each do |rental| %>
      <tr>
        <td><%= link_to rental.to_param, rental_path(rental) %></td>
        <td><%= link_to rental.film, film_path(rental.film) %></td>
        <td><%= rental.rental_date.to_formatted_s(:db) %></td>
        <td><%= rental.return_date.to_formatted_s(:db) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>

<p>No rentals found.</p>

<% end %>

app/views/films/show.html.erb
<br><br>

<table class="table table-condensed">
  <% @film.attributes.each do |key, value| %>
    <tr>
      <td><%= label_tag(key) %></td>
      <td><%= value %></td>
    </tr>
  <% end %>
  <tr>
    <td><%= label_tag :actors %></td>
    <td>
    <% @film.actors.each do |actor| %>
      <%= link_to actor.full_name, actor_path(actor) %>&emsp;
    <% end %>
    </td>
  </tr>
  <tr>
    <td><%= label_tag :category %></td>
    <td><%= link_to @film.category.name, '#' %></td>
  </tr>
</table>

<%= link_to 'Back to films', films_path %>

app/views/rentals/index.html.erb
<h1>Rentals</h1>

<% if @rentals.unreturned.any? %>

<h3>Unreturned rentals</h3>

<table>
  <thead>
    <th>Rental ID</th>
    <th>Title</th>
    <th>Customer</th>
    <th>Rental date</th>
  </thead>
  <tbody>
    <% @rentals.unreturned.each do |rental| %>
      <tr>
        <td><%= link_to rental.to_param, rental_path(rental) %></td>
        <td><%= link_to rental.film, film_path(rental.film) %></td>
        <td><%= link_to rental.customer.full_name, customer_path(rental.customer) %></td>
        <td><%= rental.rental_date.to_formatted_s(:db) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Returned rentals</h3>

<% end %>

<% if @rentals.returned.any? %>

<table>
  <thead>
    <th>Rental ID</th>
    <th>Title</th>
    <th>Customer</th>
    <th>Rental date</th>
    <th>Return date</th>
  </thead>
  <tbody>
    <% @rentals.returned.each do |rental| %>
      <tr>
        <td><%= link_to rental.to_param, rental_path(rental) %></td>
        <td><%= link_to rental.film, film_path(rental.film) %></td>
        <td><%= link_to rental.customer.full_name, customer_path(rental.customer) %></td>
        <td><%= rental.rental_date.to_formatted_s(:db) %></td>
        <td><%= rental.return_date.to_formatted_s(:db) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>

<p>No rentals found.</p>

<% end %>

app/views/rentals/returned.html.erb
<h1>Rentals</h1>

<ul class="nav nav-tabs">
  <li><%= link_to "Unreturned rentals", unreturned_rentals_path %></li>
  <li class="active"><%= link_to "Returned rentals", returned_rentals_path %></li>
</ul>

<% if @rentals.any? %>

<table class="table table-condensed">
  <thead>
    <th>Rental ID</th>
    <th>Title</th>
    <th>Customer</th>
    <th>Rental date</th>
    <th>Return date</th>
  </thead>
  <tbody>
    <% @rentals.returned.each do |rental| %>
      <tr>
        <td><%= link_to rental.to_param, rental_path(rental) %></td>
        <td><%= link_to rental.film, film_path(rental.film) %></td>
        <td><%= link_to rental.customer.full_name, customer_path(rental.customer) %></td>
        <td><%= rental.rental_date.to_formatted_s(:db) %></td>
        <td><%= rental.return_date.to_formatted_s(:db) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @rentals %>

<% else %>

<p>No rentals found.</p>

<% end %>

app/views/rentals/unreturned.html.erb
<h1>Rentals</h1>

<ul class="nav nav-tabs">
  <li class="active"><%= link_to "Unreturned rentals", unreturned_rentals_path %></li>
  <li><%= link_to "Returned rentals", returned_rentals_path %></li>
</ul>

<% if @rentals.any? %>

<table class="table table-condensed">
  <thead>
    <th>Rental ID</th>
    <th>Title</th>
    <th>Customer</th>
    <th>Rental date</th>
    <th>Due date</th>
  </thead>
  <tbody>
    <% @rentals.unreturned.each do |rental| %>
      <tr>
        <td><%= link_to rental.to_param, rental_path(rental) %></td>
        <td><%= link_to rental.film, film_path(rental.film) %></td>
        <td><%= link_to rental.customer.full_name, customer_path(rental.customer) %></td>
        <td><%= rental.rental_date.to_formatted_s(:db) %></td>
        <td><%= rental.due_date.to_formatted_s(:db) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @rentals %>

<% else %>

<p>No rentals found.</p>

<% end %>